# Generated by Django 4.0.5 on 2022-07-18 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('otp', models.IntegerField(default=123)),
                ('is_verify', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField(blank=True, default=True, null=True)),
                ('gender', models.BooleanField(blank=True, default=True, null=True)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('bloodgroup', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.FloatField(blank=True, max_length=10, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.FloatField(blank=True, max_length=10, null=True)),
                ('patient_address', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('qualification', models.CharField(blank=True, max_length=30, null=True)),
                ('specification', models.CharField(blank=True, max_length=50, null=True)),
                ('availabal_time', models.CharField(blank=True, max_length=50, null=True)),
                ('experiance', models.CharField(blank=True, max_length=50, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=50, null=True)),
                ('clinic_city', models.CharField(blank=True, max_length=50, null=True)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('pic', models.FileField(default='media/default_doc.png', upload_to='media/images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_data', models.DateField(max_length=30)),
                ('a_time', models.CharField(max_length=30)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('doc_note', models.TextField(blank=True)),
                ('case_status', models.CharField(max_length=30)),
                ('Doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
    ]
